host: localhost
port: 43007
max_conn: 1

asr:
  host: "localhost"
  port: 4007
unit:
  host: "localhost"
  port: 4008
llm:
  host: "localhost"
  port: 4003
# llm:
#   host: 140.112.21.20
#   port: 4003
tts:
  host: "localhost"
  port: 4004
