host: "localhost"
# port: 16010
#host: "localhost"
port: 4007
max_conn: 1

language: zh
min-chunk-size: 0.3
model: large-v2
backend: faster-whisper
buffer_trimming: segment
vad: True 
buffer_trimming_sec: 15
